routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/customers', 'HomeController@index')->name('customers');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/stores/{store}/products', 'Store\StoreController@products')->name('stores.products.index');
    Route::get('/stores/{store}/products/create', 'Store\ProductController@create')->name('stores.products.create');
    Route::post('/stores/{store}/products/store', 'Store\ProductController@store')->name('stores.products.store');
    Route::get('/stores/{store}/products/{product}', 'Store\ProductController@edit')->name('stores.products.edit');
    Route::put('/stores/{store}/products/{product}', 'Store\ProductController@update')->name('stores.products.update');
    Route::delete('/stores/{store}/products/{product}', 'Store\ProductController@destroy')->name('stores.products.destroy');

    Route::get('/stores/{id}/add_remove_admin', 'Store\StoreController@addRemoveAdmin')->name('stores.add_remove_admin');
    Route::post('/stores/{store}/add_admin/{user}', 'Store\StoreController@addAdmin')->name('stores.add_admin');
    Route::post('/stores/{store}/add_remove/{user}', 'Store\StoreController@removeAdmin')->name('stores.remove_admin');

//    Route::resource('products', 'Store\ProductController');
    Route::resource('stores', 'Store\StoreController');
});
//Route::get('/products', 'Store\ProductController@index')->name('products');
//Route::get('/product/{id}', 'Store\ProductController@edit')->name('edit_product');
//Route::get('/product/{id}/destroy', 'Store\ProductController@destroy')->name('destroy_product');
//Route::get('/product/{id}/create', 'Store\ProductController@destroy')->name('destroy_product');

app/Store.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Store
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $admins
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $customers
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $users
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Store newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Store newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Store query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Store whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Store whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Store whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Store whereUpdatedAt($value)
 */
class Store extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'address', 'city', 'pst',
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function customers()
    {
        return $this->belongsToMany(User::class)->withPivot(['role_id'])->where('role_id', 1);
    }

    public function admins()
    {
        return $this->belongsToMany(User::class)->withPivot(['role_id'])->where('role_id', 3);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    public function addAdminUser(User $user)
    {
        $role_store_admin = Role::where('name', 'store_admin')->first();
        if (!$user->hasRole('store_admin')) {
            $user->roles()->attach($role_store_admin);
        }
        $user->stores()->attach($this, ['role_id' => $role_store_admin->id]);
    }

    public function removeAdminUser(User $user)
    {
        $role_store_admin = Role::where('name', 'store_admin')->first();
        $user->stores()->detach($this, ['role_id' => $role_store_admin->id]);

        if ($user->stores->count() == 0) {
            $user->roles()->detach($role_store_admin);
        }
    }
}

app/Http/Controllers/Store/ProductController.php
<?php

namespace App\Http\Controllers\Store;

use App\Store;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Validator;
use App\Product;
use Symfony\Component\Debug\Exception\FatalThrowableError;

class ProductController extends Controller
{
    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'price' => ['required', 'numeric'],
            'vat' => ['required', 'numeric'],
            'ean' => ['required', 'string'],
        ]);
    }

    public function index(Request $request, Store $store)
    {
        if (!$request->user()) {
            abort(403);
        }

        $request->user()->authorizeRoles(['admin', 'store_admin']);

        return view("store/product/products", [
            'products' => Product::all(),
            'store' => $store
        ]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @param Store $store
     * @return \Illuminate\Http\Response
     */
    public function create(Store $store)
    {
        return view("store/product/create_product", ['store'=>$store]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Store $store
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Store $store)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);
        $data = $request->all();
        $this->validator($data)->validate();

        $image = $request->file("image");
        $image->filename = sprintf("%s.%s", time(), $image->getClientOriginalExtension());
        $destinationPath = public_path('/images');

        $image->move($destinationPath, $image->filename);

        $data['image'] = $image->filename;

        $store->products()->save(new Product($data));

        return redirect(route('stores.products.index', ['store' => $store]))->with('success', 'Product has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param Store $store
     * @param Product $product
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function edit(Request $request, Store $store, Product $product)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        return view("store/product/edit_product", ['product' => $product, 'store' => $store]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Product $product
     * @param Store $store
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function update(Request $request, Store $store, Product $product)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        $this->validator($request->all())->validate();

        $product->update($request->all());

        return redirect(route('stores.products.index', ['store' => $store]))->with('success', 'Product has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Store $store
     * @param Product $product
     * @return \Illuminate\Http\Response
     * @internal param int $id
     */
    public function destroy(Store $store, Product $product)
    {
        $product->delete();
        return redirect(route('stores.products.index', ['store' => $store]))->with('success', 'Product has been deleted!');
    }
}

app/Http/Controllers/Store/StoreAdminController.php
<?php

namespace App\Http\Controllers\Store;

use App\Store;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class StoreAdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $request->user()->authorizeRoles(['admin']);

        return view('store/admins/store_admins', ['stores' => Store::all()]);
    }
}

app/Http/Controllers/Store/StoreController.php
<?php

namespace App\Http\Controllers\Store;

use App\Product;
use App\Store;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class StoreController extends Controller
{
    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'address' => ['required', 'string'],
            'city' => ['required', 'string'],
            'pst' => ['required', 'numeric', 'between:1000,9999'],
        ]);
    }

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        if ($request->user()->hasRole('admin')) {
            $stores = Store::all();
        } else {
            $stores = $request->user()->stores;
        }

        return view('store/store/stores', ['stores' => $stores, 'user' => $request->user()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        return view("store/store/create_store");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        $data = $request->all();
        $this->validator($data)->validate();
        Store::create($data);


        return redirect(route('stores.index'))->with('success', 'Store has been created.');
    }

    public function edit(Request $request, $id)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        return view('store/store/edit_store', ['store' => Store::whereId($id)->first()]);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        $this->validator($request->all())->validate();

        Store::whereId($id)->first()->update($request->all());

        return redirect(route('stores.index'))->with('success', 'Store has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $request->user()->authorizeRoles(['admin', 'store_admin']);

        Store::destroy($id);
        return redirect(route('stores.index'))->with('success', 'Store has been deleted!');
    }

    public function addRemoveAdmin(Request $request, $id)
    {
        $request->user()->authorizeRoles(['admin']);

        return view('store/store/add_remove_admin', ['store'=> Store::whereId($id)->first(), 'users' => User::all()]);
    }

    public function addAdmin(Request $request, Store $store, User $user)
    {
        $request->user()->authorizeRoles(['admin']);

        $store->addAdminUser($user);
        return redirect(route('stores.add_remove_admin', ['id' => $store['id']]))->with('success', 'Admin has been added.');
    }

    public function removeAdmin(Request $request, Store $store, User $user)
    {
        $request->user()->authorizeRoles(['admin']);

        $store->removeAdminUser($user);
        return redirect(route('stores.add_remove_admin', ['id' => $store['id']]))->with('success', 'Admin has been removed.');
    }

    public function products(Store $store)
    {
        return view("store/product/products", [
            'products' => $store->products,
            'store' => $store,
        ]);
    }
}

resources/views/store/store/add_remove_admin.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Add/remove store admin for ') }}[{{ $store['name'] }}]</div>

                    <div class="card-body">
                        @if (session('success'))
                            <div class="alert alert-success" role="alert">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif

                            <ul>
                                @foreach ($users as $key => $user)
                                    <li class="mb-1">
                                        @if ($user->isStoreAdmin($store))
                                            <form class="d-inline-block" method="POST" action="{{ route('stores.remove_admin', ['id' => $store['id'], 'user_id' => $user['id']]) }}">
                                                @csrf
                                                <button class="mr-2 btn btn-danger"><i class="fas fa-minus"></i></button>
                                            </form>
                                        @else
                                            <form class="d-inline-block" method="POST" action="{{ route('stores.add_admin', ['id' => $store['id'], 'user_id' => $user['id']]) }}">
                                                @csrf
                                                <button class="mr-2 btn btn-success"><i class="fas fa-plus"></i></button>
                                            </form>
                                        @endif
                                        {{ $user['name'] }}
                                    </li>
                                @endforeach
                            </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/store/store/create_store.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit store') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('stores.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                                <div class="col-md-6">
                                    <input id="address" type="text" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" value="{{ old('address') }}" required autofocus>

                                    @if ($errors->has('address'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="city" class="col-md-4 col-form-label text-md-right">{{ __('City') }}</label>

                                <div class="col-md-6">
                                    <input id="city" type="text" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city') }}" required autofocus>

                                    @if ($errors->has('city'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('city') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="pst" class="col-md-4 col-form-label text-md-right">{{ __('Postal number') }}</label>

                                <div class="col-md-6">
                                    <input id="pst" type="text" class="form-control{{ $errors->has('pst') ? ' is-invalid' : '' }}" name="pst" value="{{ old('pst') }}" required autofocus>

                                    @if ($errors->has('pst'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('pst') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/store/store/edit_store.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit store') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('stores.update', ["id" => $store['id']]) }}">
                            @csrf

                            @method('PUT')

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $store['name']) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="address" class="col-md-4 col-form-label text-md-right">{{ __('Address') }}</label>

                                <div class="col-md-6">
                                    <input id="address" type="text" class="form-control{{ $errors->has('address') ? ' is-invalid' : '' }}" name="address" value="{{ old('address', $store['address']) }}" required autofocus>

                                    @if ($errors->has('address'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="city" class="col-md-4 col-form-label text-md-right">{{ __('City') }}</label>

                                <div class="col-md-6">
                                    <input id="city" type="text" class="form-control{{ $errors->has('city') ? ' is-invalid' : '' }}" name="city" value="{{ old('city', $store['city']) }}" required autofocus>

                                    @if ($errors->has('city'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('city') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="pst" class="col-md-4 col-form-label text-md-right">{{ __('Postal number') }}</label>

                                <div class="col-md-6">
                                    <input id="pst" type="text" class="form-control{{ $errors->has('pst') ? ' is-invalid' : '' }}" name="pst" value="{{ old('pst', $store['pst']) }}" required autofocus>

                                    @if ($errors->has('pst'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('pst') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/store/store/stores.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Stores</div>

                    <div class="card-body">

                        <h1>
                            List of stores
                            @if ($user->hasRole('admin'))
                                <a href="{{ route('stores.create') }}" class="btn btn-primary float-right">Add new <i class="fas fa-plus"></i></a>
                            @endif
                        </h1>
                        <table class="table mt-4">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Store name</th>
                                @if ($user->hasRole('admin'))
                                    <th scope="col">Number of admins</th>
                                @endif
                                <th scope="col">Products</th>
                                <th scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($stores as $key => $store)
                                <tr>
                                    <th scope="row">{{$key+1}}</th>
                                    <td>{{ $store['name'] }}</td>

                                    @if ($user->hasRole('admin'))
                                        <td>
                                            {{ count($store->admins) }}
                                            <a class="ml-2 btn btn-primary" href="{{ route('stores.add_remove_admin', $store['id']) }}" title="Add or remove admins"><i class="fas fa-user"></i></a>
                                        </td>
                                    @endif
                                    <td>
                                        {{ $store->products->count() }}
                                        <a class="ml-2 btn btn-primary" href="{{ route('stores.products.index', $store['id']) }}" title="Edit products"><i class="fas fa-boxes"></i></a>
                                    </td>
                                    <td class="text-right">
                                        <a class="ml-2 btn btn-primary" href="{{ route('stores.edit', $store['id']) }}" title="edit"><i class="fas fa-edit"></i></a>
                                        <form class="delete-button" action="{{ route('stores.destroy', $store['id'])}}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger" type="submit"><i class="fas fa-times"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection