routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/customers', 'HomeController@index')->name('customers');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/stores/{store}/products', 'Store\StoreController@products')->name('stores.products.index');
    Route::get('/stores/{store}/products/create', 'Store\ProductController@create')->name('stores.products.create');
    Route::post('/stores/{store}/products/store', 'Store\ProductController@store')->name('stores.products.store');
    Route::get('/stores/{store}/products/{product}', 'Store\ProductController@edit')->name('stores.products.edit');
    Route::put('/stores/{store}/products/{product}', 'Store\ProductController@update')->name('stores.products.update');
    Route::delete('/stores/{store}/products/{product}', 'Store\ProductController@destroy')->name('stores.products.destroy');

    Route::get('/stores/{id}/add_remove_admin', 'Store\StoreController@addRemoveAdmin')->name('stores.add_remove_admin');
    Route::post('/stores/{store}/add_admin/{user}', 'Store\StoreController@addAdmin')->name('stores.add_admin');
    Route::post('/stores/{store}/add_remove/{user}', 'Store\StoreController@removeAdmin')->name('stores.remove_admin');

//    Route::resource('products', 'Store\ProductController');
    Route::resource('stores', 'Store\StoreController');
});
//Route::get('/products', 'Store\ProductController@index')->name('products');
//Route::get('/product/{id}', 'Store\ProductController@edit')->name('edit_product');
//Route::get('/product/{id}/destroy', 'Store\ProductController@destroy')->name('destroy_product');
//Route::get('/product/{id}/create', 'Store\ProductController@destroy')->name('destroy_product');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://cdn.jsdelivr.net/jsbarcode/3.6.0/JsBarcode.all.min.js" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Easy Shopping') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            @if (Auth::user()->hasRole('admin') || Auth::user()->hasRole('store_admin'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('stores.index') }}">{{ __('Stores') }}</a>
                                </li>
                            @endif

                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <script>
        setTimeout(function(){
        var htmlCollectionArray = document.getElementsByClassName('barcode');
        Array.prototype.forEach.call(htmlCollectionArray, function(el, i) {
            console.log(el.getAttribute("ean"), el.id);
            JsBarcode("#"+el.id, el.getAttribute("ean"));
        });
        }, 500);
    </script>

</body>
</html>